# Generated by Django 4.2.1 on 2023-05-10 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0005_alter_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
