# Generated by Django 4.2.1 on 2023-05-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0010_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='customer_images'),
        ),
    ]
